
services:

    Gweb\TecdocBundle\Api\Builder\:
        resource: '../../Api/Builder'
        arguments:
            - '@Gweb\TecdocBundle\Service\EntityManager'
            - '@Gweb\TecdocBundle\Service\TranslateManager'

    Gweb\TecdocBundle\Api\Controller\ArticleController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Gweb\TecdocBundle\Api\Builder\ArticleBuilder'

    Gweb\TecdocBundle\Api\Controller\CategoryController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Gweb\TecdocBundle\Api\Builder\CategoryBuilder'

    Gweb\TecdocBundle\Api\Controller\SupplierController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Gweb\TecdocBundle\Api\Builder\SupplierBuilder'

    Gweb\TecdocBundle\Api\Controller\VehicleController:
        tags: ['controller.service_arguments']
        arguments:
            - '@Gweb\TecdocBundle\Api\Builder\VehicleBuilder'


    Gweb\TecdocBundle\Command\ExtractCommand:
        tags: ['console.command']
        arguments:
            - '@parameter_bag'

    Gweb\TecdocBundle\Command\ImportCommand:
        tags: ['console.command']
        arguments:
            - '@Gweb\TecdocBundle\Service\ImportManager'


    Gweb\TecdocBundle\Service\EntityManager:
        arguments:
            - '@doctrine.orm.tecdoc_entity_manager'

    Gweb\TecdocBundle\Service\ImportManager:
        arguments:
            - '@Gweb\TecdocBundle\Service\EntityManager'
            - '%gweb_tecdoc.dir_data_reference%'
            - '%gweb_tecdoc.dir_data_supplier%'

    Gweb\TecdocBundle\Service\TranslateManager:
        arguments:
            - '@Gweb\TecdocBundle\Service\EntityManager'
            - '@request_stack'
            - '%gweb_tecdoc.translator_default_locale%'

    Gweb\TecdocBundle\EventListener\TranslateListener:
        arguments:
            - '@Gweb\TecdocBundle\Service\TranslateManager'
            - '%gweb_tecdoc.translator_autoload%'
        tags:
            - { name: doctrine.orm.entity_listener, entity_manager: tecdoc }
